"""Added Product model

Revision ID: 65c3b404949a
Revises: a4567d6d8768
Create Date: 2025-03-07 15:18:29.089200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c3b404949a'
down_revision = 'a4567d6d8768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('current_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('previous_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('product_picture', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sale', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('size_small', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size_medium', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size_large', sa.Integer(), nullable=True))
        batch_op.drop_column('image_file')
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('size_large')
        batch_op.drop_column('size_medium')
        batch_op.drop_column('size_small')
        batch_op.drop_column('sale')
        batch_op.drop_column('quantity')
        batch_op.drop_column('category')
        batch_op.drop_column('rating')
        batch_op.drop_column('color')
        batch_op.drop_column('product_picture')
        batch_op.drop_column('previous_price')
        batch_op.drop_column('current_price')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
